version: '3.9'
services:
  app:
    container_name: heyemoji-bitops
    env_file: .env
    restart: always
    build: .
    ports:
      - 3334:3334
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data